### Create a new user - this one will only get a USER role by default
POST {{url}}/auth/register/

{
    "username": "user",
    "password": "test123"
}

###
POST {{url}}/auth/login/

{
    "username": "user",
    "password": "test123"
}

> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}

### Add admin role to user
POST {{url}}/auth/user/addrole/
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
    "role": "admin"
}
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Get all trips
GET {{url}}/trips

### Get trip by id
GET {{url}}/trips/1
Authorization: Bearer {{jwt_token}}


### Create trip
POST {{url}}/trips
Content-Type: application/json
Authorization: Bearer {{jwt_token}}


{
  "name": "TestTrip",
  "price": 212.0,
  "category": "SNOW",
  "start_time": "10:00",
  "end_time": "12:00",
  "longitude": 12.34567,
  "latitude": 54.32109
}

### Update by id
PUT {{url}}/trips/11
Content-Type: application/json
Authorization: Bearer {{jwt_token}}


{
  "name": "NewName"
}

### Delete trip by id
DELETE {{url}}/trips/10
Authorization: Bearer {{jwt_token}}


### Add trip to guide
PUT {{url}}/trips/1/guides/2
Authorization: Bearer {{jwt_token}}


### Filter Trips by category
GET {{url}}/trips/category/FOREST
Authorization: Bearer {{jwt_token}}

