### Get all trips
GET {{url}}/trips

### Get trip by id
GET {{url}}/trips/1

### Create trip
POST {{url}}/trips
Content-Type: application/json

{
  "name": "TestTrip",
  "price": 212.0,
  "category": "SNOW",
  "start_time": "10:00",
  "end_time": "12:00",
  "longitude": 12.34567,
  "latitude": 54.32109
}

### Update by id
PATCH {{url}}/trips/1
Content-Type: application/json

{
  "name": "TestTrip",
  "price": 212.0,
  "category": "SNOW",
  "start_time": "10:00",
  "end_time": "12:00",
  "longitude": 12.34567,
  "latitude": 54.32109
}

### Delete trip by id
DELETE {{url}}/trips/1

### Add trip to guide
PUT {{url}}/trips/1/guides/3

### Filter Trips by category
GET {{url}}/trips/category/FOREST

